server:
  port: 8081
#slf4j配置
logging:
  pattern:
    console: "%d - %msg%n"
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/warehouse?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
  thymeleaf:
    cache: false



